volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  server:
    image: lwserver
    platform: linux/x86_64
    build: server
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_ADDRESS=localhost:5432
      - ALLOWED_ORIGIN=localhost:3000
  client:
    image: lwclient
    build: client
