volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  server:
    image: lwserver
    build: server
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_ADDRESS=postgres:5432
      - ALLOWED_ORIGIN=http://localhost:3000
  client:
    image: lwclient
    build: client
    ports:
      - 3000:80
